# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LnuChat' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for LnuChat
   pod 'Parse'

  target 'LnuChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LnuChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
